### ISSUE TITLE
Can you add example for batch processing of predictions

### ISSUE THREAD

**Issue by kdcllc** [jeffprosise/ML.NET#2]
@jeffprosise,

I enjoyed your presentation from the other day it was very informative. Can you expand your examples to include batch predictions?

Thanks

**Comment by jeffprosise** [comment]
Yes, I will! Meanwhile, here is one example that demonstrates how to do it:

https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis#use-the-model-for-prediction

It's a little unintuitive because  you call Transform() on the model and pass it an IDataView containing the batch input. But it's a good example to go by. I may write an example that performs batch processing on a collection of images.

**Comment by kdcllc** [comment]
@jeffprosise thank you for the pointer. Batch processing can be an important issue for AspNetCore applications.
